// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValidateModel.Models;

namespace ValidateModel.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20191012035130_ValidateModel.DBContext")]
    partial class ValidateModelDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ValidateModel.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenKhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("ValidateModel.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreditCard");

                    b.Property<double>("Diem");

                    b.Property<string>("Email");

                    b.Property<string>("GhiChu");

                    b.Property<double>("HeSo");

                    b.Property<string>("Hinh");

                    b.Property<string>("HoTen");

                    b.Property<string>("MaBaoMat");

                    b.Property<string>("MaKhoa");

                    b.Property<string>("NgaySinh");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("ValidateModel.Models.SinhVien", b =>
                {
                    b.HasOne("ValidateModel.Models.Khoa", "khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa");
                });
#pragma warning restore 612, 618
        }
    }
}
