// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.Models;

namespace QuanLySinhVien.Migrations
{
    [DbContext(typeof(QLSVContext))]
    [Migration("20191130155346_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLySinhVien.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenKhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.LopHocPhan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HocKy");

                    b.Property<string>("MaHocPhan");

                    b.Property<string>("MaMon");

                    b.Property<string>("MaSV");

                    b.Property<int>("NamHoc");

                    b.HasKey("ID");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaSV");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMon")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenMon");

                    b.HasKey("MaMon");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DienThoai");

                    b.Property<string>("HoTen");

                    b.Property<string>("Makhoa");

                    b.Property<DateTime>("NgaySinh");

                    b.HasKey("MaSV");

                    b.HasIndex("Makhoa");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.LopHocPhan", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMon");

                    b.HasOne("QuanLySinhVien.Models.SinhVien", "SinhVien")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaSV");
                });

            modelBuilder.Entity("QuanLySinhVien.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLySinhVien.Models.Khoa", "khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("Makhoa");
                });
#pragma warning restore 612, 618
        }
    }
}
